[workspace]
resolver = "3"
members = [
    "core",
    "libs/chat",
    "libs/db",
    "libs/llm",
    "libs/llm_client",
    "libs/queue",
    "libs/uzor_plugin",
]

[workspace.package]
edition = "2024"
rust-version = "1.95.0"

[workspace.dependencies]
actix-web = { version = "4.14" }
ahash = { version = "*" }
base64 = { version = "*" }
futures = { version = "*" }
josekit = { version = "*" }
proc-macro2 = { version = "*" }
quote = { version = "1.0" }
reqwest = { version = "*", features = ["stream", "json", "form"] }
sqlx = { version = "*", features = [
    "postgres",
    "runtime-tokio",
    "time",
] } # пока версия sqlx 0.8.6, т.к последняя (0.9.0) ругается на возможные инъекции в динамичных sql строках
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
syn = { version = "2.0", features = ["full"] }
thiserror = { version = "*" }
time = { version = "*", features = [
    "macros",
    "formatting",
    "parsing",
    "serde",
] }
tokio = { version = "*", features = [
    "macros",
    "rt-multi-thread",
    "sync",
] } # Currently "1.52.3"
tokio_util = "*" # Currently "0.7.18"
toml = { version = "1.1.2" }
tracing = { version = "*" } # "0.1.44"
tracing-appender = { version = "*" } # "0.2.5"
tracing-subscriber = { version = "*", features = [
    "json",
    "registry",
] } # "0.3.23"


[profile.release]
opt-level = 3
debug = 0
strip = true
lto = true
incremental = true
codegen-units = 4

[profile.release.package."*"]
debug = false
opt-level = 3
strip = true
incremental = true
codegen-units = 4
