[workspace]
resolver = "3"
members = [
    "core",
    "libs/chat",
    "libs/db",
    "libs/llm",
    "libs/queue"
]

[workspace.dependencies]
# пока версия sqlx 0.8.6, т.к последняя (0.9.0) ругается на возможные инъекции в динамичных sql строках
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "time"] }
ahash = { version = "*" }
thiserror = { version = "*" }
quote = { version = "1.0" }
proc-macro2 = { version = "*" }
tracing = { version = "*" }
time = { version = "*", features = ["macros", "formatting", "parsing", "serde"] }
toml = { version = "1.1.2" }
syn = { version = "2.0", features = ["full"] }
tokio = { version = "*", features = ["full"] }
reqwest = { version = "*", features = ["json", "form"] }
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }

[profile.release]
opt-level = 3
debug = 0
strip = true
lto = true
incremental = true
codegen-units = 4

[profile.release.package."*"]
debug = false
opt-level = 3
strip = true
incremental = true
codegen-units = 4